In [7]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


You should consider upgrading via the 'C:\Users\Yemzie\AppData\Local\Programs\Python\Python310\python.exe -m pip install --upgrade pip' command.


In [9]:
# Numpy Task 1
# Create a 1D array of numbers from 0 to 9

import numpy as np

x = np.arange(10)
print("Array from 0 to 10:")
print(x)


Array from 0 to 10:
[0 1 2 3 4 5 6 7 8 9]


In [18]:
# Numpy task 2
# Create a 3×3 NumPy array of all Boolean value Trues

threebythree_array_boolean = np.full((3,3), True, dtype=bool)
print(threebythree_array_boolean)
                                     

[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]


In [64]:
# Numpy Task 3
# Extract all odd numbers from array of 1 - 10

odd_numbers = np.array([1,2,3,4,5,6,7,8,9,10])
for num in odd_numbers:
    if num % 2 != 0:
        print(num, end = "" ,)

 


13579

In [65]:
# OR

odd_numbers = np.array([1,2,3,4,5,6,7,8,9,10])
odd_numbers[odd_numbers % 2 == 1]

array([1, 3, 5, 7, 9])

In [69]:
# Task 4
# Replace all odd numbers in an array of 1 10 with the value -1

odd_numbers = np.array([1,2,3,4,5,6,7,8,9,10])
odd_numbers[odd_numbers % 2 == 1] = -1
print(odd_numbers)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [77]:
# Task 5
# Convert a 1D array to a 2D array with 2 rows

# 1D array

array1 = np.array([10, 20, 30,40])

# 2D array
newArray = array1.reshape(2, 2)

print(newArray)

[[10 20]
 [30 40]]


In [83]:
# Task 6
# Create two arrays a and b, stack these two arrays vertically use the np.dot and
# np.sum to calculate totals

a = np.arange (1,17).reshape(4,4)
b = np.arange (17, 33).reshape (4,4)

c = np.dot(a,b)
sum = np.sum(c)

print (sum)

13648
